const $=id=>document.getElementById(id),K="recalldeck-v3";let cards=JSON.parse(localStorage.getItem(K)||localStorage.getItem("recalldeck-v2")||localStorage.getItem("recalldeck-v1")||"[]"),cur=null,rev=false,queue=[],pos=0,sessionActive=false,sessions=+localStorage.getItem("recalldeck-sessions")||0,pendingImport=null;
const day=()=>new Date().toISOString().slice(0,10),due=c=>!c.next||c.next<=day(),esc=s=>String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}function save(){localStorage.setItem(K,JSON.stringify(cards));renderStats();list()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function renderStats(){let r=cards.reduce((s,c)=>s+(c.reviews||0),0),g=cards.reduce((s,c)=>s+(c.good||0),0),l=cards.filter(c=>(c.level||0)>=4).length,m=cards.length?Math.round(cards.reduce((s,c)=>s+Math.min(100,(c.level||0)*20),0)/cards.length):0;$("due").textContent=cards.filter(due).length;$("learned").textContent=l;$("accuracy").textContent=r?Math.round(g/r*100)+"%":"0%";$("reviews").textContent=r;$("total").textContent=cards.length;$("important").textContent=cards.filter(c=>c.star).length;$("mastery").textContent=m+"%";$("bar").style.width=m+"%";$("sessions").textContent=sessions}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function startSession(){let d=cards.filter(due);if(!d.length){$("studyArea").classList.add("hidden");$("empty").classList.remove("hidden");return}let v=$("limit").value,lim=v==="all"?d.length:v==="custom"?Math.max(1,+$("customLimit").value||1):+v;queue=($("random").checked?shuffle(d):d).slice(0,Math.min(lim,d.length));pos=0;sessionActive=true;$("sessionInfo").classList.remove("hidden");showNext()}
function showNext(){if(pos>=queue.length){endSession();return}cur=queue[pos];rev=false;$("sessionPos").textContent=(pos+1)+" / "+queue.length;$("sessionMode").textContent=$("random").checked?"🔀 Random order":"Sequential";$("front").textContent=cur.q;$("back").textContent=cur.a;$("front").classList.remove("hidden");$("back").classList.add("hidden");$("ratings").classList.add("hidden");$("hint").textContent="Tap to reveal";$("tag").textContent=cur.star?"⭐ IMPORTANT":cur.tag||cur.deck;$("count").textContent=cards.filter(due).length+" due";$("studyArea").classList.remove("hidden");$("empty").classList.add("hidden")}
function endSession(){sessionActive=false;cur=null;sessions++;localStorage.setItem("recalldeck-sessions",sessions);$("sessionInfo").classList.add("hidden");renderStats();toast("Session complete 🎉")}
function addDays(n){let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function rate(k){let c=cards.find(x=>x.id===cur.id);c.reviews=(c.reviews||0)+1;c.good=(c.good||0)+(k==="again"?0:1);c.level=Math.max(0,(c.level||0)+(k==="again"?-1:k==="hard"?0:k==="good"?1:2));c.next=k==="again"?new Date(Date.now()+600000).toISOString().slice(0,16):addDays({hard:1,good:3,easy:7}[k]);c.reviewDates=c.reviewDates||[];c.reviewDates.push(day());save();pos++;showNext()}
function add(){let q=$("q").value.trim(),a=$("a").value.trim();if(!q||!a){alert("Enter both question and answer.");return}cards.push({id:uid(),q,a,deck:$("deck").value.trim()||"General",tag:$("tagInput").value.trim(),star:$("star").checked,level:0,reviews:0,good:0,next:day(),reviewDates:[]});$("q").value="";$("a").value="";$("tagInput").value="";$("star").checked=false;save();go("study");toast("Card added")}
function list(){let q=$("search").value.toLowerCase(),a=cards.filter(c=>(c.q+" "+c.a+" "+c.deck+" "+c.tag).toLowerCase().includes(q));$("list").innerHTML=a.map(c=>`<div class="listCard"><main><b>${c.star?"⭐ ":""}${esc(c.q)}</b><small>${esc(c.deck)}${c.tag?" • "+esc(c.tag):""} • ${due(c)?"Due now":"Next "+c.next}</small></main><button class="mini" data-s="${c.id}">Study</button><button class="mini" data-x="${c.id}">×</button></div>`).join("");$("none").classList.toggle("hidden",a.length>0);document.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>{cur=cards.find(c=>c.id===b.dataset.s);queue=[cur];pos=0;sessionActive=true;go("study");showNext()});document.querySelectorAll("[data-x]").forEach(b=>b.onclick=()=>{if(confirm("Delete card?")){cards=cards.filter(c=>c.id!==b.dataset.x);save()}})}
function go(t){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(t).classList.remove("hidden");if(t==="cards")list();if(t==="study"&&!sessionActive)startSession()}
function normalize(x,i){if(!x||typeof x!=="object")return null;let q=x.front??x.question??x.word??x.term??x.q,a=x.back??x.answer??x.meaning??x.definition??x.a;if(q===undefined||a===undefined)return null;return{id:String(x.id||uid()+i),q:String(q),a:String(a),deck:String(x.deck??x.category??"General"),tag:String(x.tag??x.topic??""),star:Boolean(x.star??x.important??false),level:Number.isFinite(+x.level)?+x.level:0,reviews:Number.isFinite(+x.reviews)?+x.reviews:0,good:Number.isFinite(+x.good)?+x.good:0,next:x.next||day(),reviewDates:Array.isArray(x.reviewDates)?x.reviewDates:[]}}
$("flash").onclick=()=>{if(!cur)return;rev=!rev;$("front").classList.toggle("hidden",rev);$("back").classList.toggle("hidden",!rev);$("ratings").classList.toggle("hidden",!rev);$("hint").textContent=rev?"Tap to hide":"Tap to reveal"};
document.querySelectorAll(".ratings button").forEach(b=>b.onclick=()=>rate(b.dataset.r));document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>go(b.dataset.tab));$("startSession").onclick=startSession;$("saveCard").onclick=add;$("search").oninput=list;$("goAdd").onclick=()=>go("add");$("limit").onchange=()=>$("customLimit").classList.toggle("hidden",$("limit").value!=="custom");
$("export").onclick=()=>{let blob=new Blob([JSON.stringify(cards,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="recalldeck-backup-"+day()+".json";a.click();URL.revokeObjectURL(a.href);toast("JSON exported")};
$("importFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let raw=JSON.parse(r.result),arr=Array.isArray(raw)?raw:(Array.isArray(raw.cards)?raw.cards:Array.isArray(raw.flashcards)?raw.flashcards:null);if(!arr)throw Error("JSON must be an array or contain a cards/flashcards array.");let valid=arr.map(normalize).filter(Boolean);pendingImport=valid;$("importPreview").textContent=`Found ${arr.length} item(s). Valid cards: ${valid.length}. ${arr.length-valid.length?arr.length-valid.length+" invalid item(s) will be skipped.":"All items look valid."}`;$("importBtn").disabled=!valid.length}catch(err){pendingImport=null;$("importPreview").textContent="Invalid JSON: "+err.message;$("importBtn").disabled=true}};r.readAsText(f)};
$("importBtn").onclick=()=>{if(!pendingImport?.length)return;if($("importMode").value==="replace")cards=pendingImport;else{let seen=new Set(cards.map(c=>(c.q+"\n"+c.a).toLowerCase()));let add= pendingImport.filter(c=>{let k=(c.q+"\n"+c.a).toLowerCase();if(seen.has(k))return false;seen.add(k);return true});cards.push(...add);toast(`${add.length} new card(s) imported`)}if($("importMode").value==="replace")toast(`${pendingImport.length} card(s) imported`);pendingImport=null;$("importFile").value="";$("importPreview").textContent="No file selected.";$("importBtn").disabled=true;save();go("cards")};
renderStats();list();if(cards.filter(due).length)startSession();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));